# Generated by Django 4.1.2 on 2022-10-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='tipoDocumento',
            field=models.CharField(choices=[('cc', 'Cedula'), ('ti', 'Tarjeta de Identidad')], default='cc', max_length=2),
        ),
    ]
