# Generated by Django 4.1.2 on 2022-10-24 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0003_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=30)),
                ('marca', models.CharField(choices=[('ren', 'Renault'), ('che', 'Chevrolet'), ('toy', 'Toyota'), ('kia', 'Kia')], default='toy', max_length=3)),
                ('modelo', models.CharField(max_length=4)),
                ('color', models.CharField(choices=[('roj', 'rojo'), ('ver', 'verde'), ('ama', 'amarillo'), ('azu', 'azul'), ('neg', 'negro'), ('bla', 'blanco')], default='roj', max_length=3)),
                ('observaciones', models.TextField(blank=True)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='vehiculo',
        ),
    ]
